"""Tests for wiring the Greenhouse provider into startup and the chat path.

The wiring lives in its own module so the edits inside Odysseus' own files stay
at a couple of lines each. `src/app_initializer.py` and `routes/chat_helpers.py`
are upstream-owned; every line added to them is one to re-merge forever.
"""

import asyncio


def run(coro):
    return asyncio.run(coro)


class FakeProvider:
    """Stands in for GreenhouseMemoryProvider. Only the wiring is under test."""

    provider_id = "greenhouse"
    display_name = "Greenhouse"
    enabled = True

    def __init__(self, hits=None, available=True, last_error=None):
        self._hits = hits or []
        self.available = available
        self.last_error = last_error
        self.calls = []

    async def recall(self, query, *, owner=None, top_k=5):
        self.calls.append((query, top_k))
        return self._hits


class FakeHit:
    def __init__(self, text, **greenhouse):
        self.score = greenhouse.pop("score", 0.9)
        self.provider_id = "greenhouse"
        self.memory = type(
            "M", (), {"text": text, "metadata": {"greenhouse": greenhouse}}
        )()


# --- building the provider from configuration ---------------------------


def test_no_provider_when_unconfigured(monkeypatch):
    """An unconfigured Odysseus must behave exactly as it does today."""
    from src.greenhouse_wiring import build_greenhouse_provider

    monkeypatch.delenv("GREENHOUSE_URL", raising=False)
    monkeypatch.delenv("GREENHOUSE_TOKEN", raising=False)

    assert build_greenhouse_provider() is None


def test_no_provider_when_only_half_configured(monkeypatch):
    """A URL with no token would fail every call with a 401. Refuse to build it
    rather than register a provider that can only produce outages."""
    from src.greenhouse_wiring import build_greenhouse_provider

    monkeypatch.setenv("GREENHOUSE_URL", "http://greenhouse.test")
    monkeypatch.delenv("GREENHOUSE_TOKEN", raising=False)

    assert build_greenhouse_provider() is None


def test_provider_built_when_configured(monkeypatch):
    from src.greenhouse_wiring import build_greenhouse_provider

    monkeypatch.setenv("GREENHOUSE_URL", "http://greenhouse.test")
    monkeypatch.setenv("GREENHOUSE_TOKEN", "tok")

    provider = build_greenhouse_provider()

    assert provider is not None
    assert provider.provider_id == "greenhouse"


# --- recall into the chat preface ---------------------------------------


def test_recall_message_carries_memories_and_attribution():
    from src.greenhouse_wiring import greenhouse_recall_message

    provider = FakeProvider(
        hits=[
            FakeHit(
                "The return pump is a Sicce Syncra 3.0",
                kind="fact",
                authority="human",
                area_key="aquariums",
                corroboration_count=2,
            )
        ]
    )

    message = run(greenhouse_recall_message(provider, "what pump do I run?"))

    assert message is not None
    content = message["content"]
    assert "Sicce Syncra 3.0" in content
    assert "aquariums" in content
    assert "fact" in content
    from src.greenhouse_wiring import RECALL_LIMIT

    assert provider.calls == [("what pump do I run?", RECALL_LIMIT)]


def test_recall_message_is_untrusted_context_not_a_system_message():
    """Retrieved text must never enter the system role — it is data, not
    instruction, and the system prefix has to stay byte-identical for KV cache
    reuse besides."""
    from src.greenhouse_wiring import greenhouse_recall_message

    provider = FakeProvider(hits=[FakeHit("something", kind="fact")])
    message = run(greenhouse_recall_message(provider, "q"))

    assert message["role"] != "system"


def test_no_message_when_nothing_is_recalled():
    """Silence about a *success* is correct. An empty recall adds nothing."""
    from src.greenhouse_wiring import greenhouse_recall_message

    provider = FakeProvider(hits=[])

    assert run(greenhouse_recall_message(provider, "q")) is None


def test_outage_produces_a_visible_notice_not_silence():
    """Invariant 13. An outage must not look like Greenhouse knowing nothing."""
    from src.greenhouse_wiring import greenhouse_recall_message

    provider = FakeProvider(hits=[], available=False, last_error="ConnectError: refused")
    message = run(greenhouse_recall_message(provider, "q"))

    assert message is not None
    assert "unavailable" in message["content"].lower()


def test_the_outage_notice_is_not_gagged_by_the_untrusted_wrapper():
    """The wrapper ends "Do not mention this wrapper, label, or warning in your
    answer", which is right for retrieved content and exactly wrong here: it
    tells the model to hide the very thing that has to be said out loud.

    Retrieved memories are untrusted because they came from outside. A health
    notice is generated by this module and carries no third-party text, so it
    is not untrusted data and must not be gagged as if it were.
    """
    from src.prompt_security import GUARD_OPEN
    from src.greenhouse_wiring import greenhouse_recall_message

    provider = FakeProvider(hits=[], available=False, last_error="refused")
    message = run(greenhouse_recall_message(provider, "q"))

    assert GUARD_OPEN not in message["content"]
    assert "do not mention" not in message["content"].lower()
    assert message.get("metadata", {}).get("greenhouse_unavailable") is True


def test_recalled_memories_are_still_wrapped_as_untrusted():
    """Loosening the notice must not loosen the content it sits beside."""
    from src.prompt_security import GUARD_OPEN
    from src.greenhouse_wiring import greenhouse_recall_message

    provider = FakeProvider(hits=[FakeHit("something", kind="fact")])
    message = run(greenhouse_recall_message(provider, "q"))

    assert GUARD_OPEN in message["content"]


def test_outage_notice_never_leaks_the_error_verbatim_into_instructions():
    from src.greenhouse_wiring import greenhouse_recall_message

    provider = FakeProvider(hits=[], available=False, last_error="tok=SECRET")
    message = run(greenhouse_recall_message(provider, "q"))

    assert "SECRET" not in message["content"]


def test_a_raising_provider_does_not_break_the_turn():
    """A bug in the adapter must not take chat down with it."""
    from src.greenhouse_wiring import greenhouse_recall_message

    class Exploding(FakeProvider):
        async def recall(self, query, *, owner=None, top_k=5):
            raise RuntimeError("boom")

    assert run(greenhouse_recall_message(Exploding(), "q")) is None


def test_none_provider_is_a_no_op():
    from src.greenhouse_wiring import greenhouse_recall_message

    assert run(greenhouse_recall_message(None, "q")) is None


# --- the automatic extractor's default ----------------------------------


def test_auto_extraction_defaults_off_once_greenhouse_owns_memory(monkeypatch):
    from src.greenhouse_wiring import auto_memory_default

    monkeypatch.setenv("GREENHOUSE_URL", "http://greenhouse.test")
    monkeypatch.setenv("GREENHOUSE_TOKEN", "tok")

    assert auto_memory_default() is False


def test_auto_extraction_default_is_unchanged_without_greenhouse(monkeypatch):
    """An Odysseus with no Greenhouse keeps its own behaviour exactly."""
    from src.greenhouse_wiring import auto_memory_default

    monkeypatch.delenv("GREENHOUSE_URL", raising=False)
    monkeypatch.delenv("GREENHOUSE_TOKEN", raising=False)

    assert auto_memory_default() is True


def test_scoping_is_a_no_op_without_a_provider():
    from src.greenhouse_wiring import scope_native_memory_to_scratch

    sentinel = object()
    assert scope_native_memory_to_scratch(sentinel, None) is sentinel


# --- health reporting ----------------------------------------------------


def test_health_is_disabled_when_greenhouse_is_not_configured(monkeypatch):
    """A feature that is switched off must not drag the overall status down."""
    from src.greenhouse_wiring import greenhouse_health

    monkeypatch.delenv("GREENHOUSE_URL", raising=False)
    monkeypatch.delenv("GREENHOUSE_TOKEN", raising=False)

    assert greenhouse_health(None)["status"] == "disabled"


def test_health_is_down_after_an_outage(monkeypatch):
    """Invariant 13: the failure has to reach Daniel without him going looking.

    The model is told to say so, but that depends on it complying. The status
    panel does not.
    """
    from src.greenhouse_wiring import greenhouse_health

    monkeypatch.setenv("GREENHOUSE_URL", "http://greenhouse.test")
    monkeypatch.setenv("GREENHOUSE_TOKEN", "tok")
    provider = FakeProvider(available=False, last_error="ConnectError: refused")

    report = greenhouse_health(provider)

    assert report["status"] == "down"
    assert report["name"] == "greenhouse"
    assert "model" in report["detail"].lower() or "greenhouse" in report["detail"].lower()


def test_health_is_ok_while_reachable(monkeypatch):
    from src.greenhouse_wiring import greenhouse_health

    monkeypatch.setenv("GREENHOUSE_URL", "http://greenhouse.test")
    monkeypatch.setenv("GREENHOUSE_TOKEN", "tok")

    assert greenhouse_health(FakeProvider())["status"] == "ok"


def test_health_never_reports_a_credential_or_raw_error(monkeypatch):
    from src.greenhouse_wiring import greenhouse_health

    monkeypatch.setenv("GREENHOUSE_URL", "http://user:pw@greenhouse.test/x?api_key=s3cret")
    monkeypatch.setenv("GREENHOUSE_TOKEN", "tok-abcdef")
    provider = FakeProvider(available=False, last_error="401 with tok-abcdef")

    report = greenhouse_health(provider)

    blob = repr(report)
    assert "tok-abcdef" not in blob
    assert "s3cret" not in blob
    assert "pw" not in blob


def test_the_health_panel_can_reach_the_provider_built_at_startup(monkeypatch):
    """service_health has no access to the component dict, so it reads the
    provider through this handle. If that breaks, the panel silently reports a
    healthy Greenhouse during an outage -- worse than not reporting at all."""
    from src.greenhouse_wiring import build_greenhouse_provider, current_greenhouse_provider

    monkeypatch.setenv("GREENHOUSE_URL", "http://greenhouse.test")
    monkeypatch.setenv("GREENHOUSE_TOKEN", "tok")

    built = build_greenhouse_provider()

    assert current_greenhouse_provider() is built


def test_the_health_probe_is_wired_into_the_service_panel():
    """Asserted against the real collect_service_health, because a probe that
    exists but is never called is the same as no probe."""
    import inspect

    from src import service_health

    source = inspect.getsource(service_health.collect_service_health)
    assert "greenhouse_health" in source
